# .github/workflows/nixos-config-check.yaml
name: nixos-config-check

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

env:
  flake: github:${{ github.repository }}/${{ github.sha }}
  nixos-host: nixos
  nix-conf: |-
    accept-flake-config = true
    always-allow-substitutes = true
    builders-use-substitutes = true
    max-jobs = auto

jobs:
  flake-check:
    name: flake check (x86_64-linux)
    runs-on: ubuntu-24.04
    steps:
      - uses: DeterminateSystems/nix-installer-action@v19
        with:
          extra-conf: ${{ env.nix-conf }}
      - uses: cachix/cachix-action@v16
        with:
          name: hexpilgrim-cache
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - name: nix flake check
        run: nix flake check '${{ env.flake }}' --impure --option allow-import-from-derivation true

  flake-show:
    name: flake show (x86_64-linux)
    runs-on: ubuntu-24.04
    steps:
      - uses: DeterminateSystems/nix-installer-action@v19
        with:
          extra-conf: ${{ env.nix-conf }}
      - uses: cachix/cachix-action@v16
        with:
          name: hexpilgrim-cache
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - name: nix flake show
        run: nix flake show '${{ env.flake }}' --impure --option allow-import-from-derivation true

  build:
    name: build nixos system (x86_64-linux)
    runs-on: ubuntu-24.04
    steps:
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: "holster"
      - uses: DeterminateSystems/nix-installer-action@v19
        with:
          extra-conf: ${{ env.nix-conf }}
      - uses: cachix/cachix-action@v16
        with:
          name: hexpilgrim-cache
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - name: build system config
        run: nix build '${{ env.flake }}#nixosConfigurations.${{ env.nixos-host }}.config.system.build.toplevel'

  input-check:
    name: validate flake input ${{ matrix.input }} [x86_64-linux]
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        input:
          - nixpkgs
          - home-manager
          - nur
          - chaotic
          - spicetify-nix
          - umu
          - nix-gaming
          - disko
          - flake-parts
          - flake-utils
          - nix-index
          - nixos-hardware
          - catppuccin
    steps:
      - uses: DeterminateSystems/nix-installer-action@v19
        with:
          extra-conf: ${{ env.nix-conf }}
      - name: verify input '${{ matrix.input }}' exists in flake
        run: |
          nix flake show --json '${{ env.flake }}' | jq -e '.inputs["${{ matrix.input }}"]' > /dev/null

  check:
    name: aggregate check
    runs-on: ubuntu-24.04
    needs:
      - flake-check
      - flake-show
      - build
      - input-check
    if: always()
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
